version: '3'
services:
  client:
    platform: linux/x86_64
    build: 
      dockerfile: Dockerfile
    environment:
      - SERVER_DOMAIN=http://backend-web-server
      - DEFAULT_LOCALE=ru
#     - NUXT_PUBLIC_APP_NAME='YaChat UI' # The name of the application
#     - NUXT_PUBLIC_TYPEWRITER=true # Whether to enable the typewriter effect, default false
#     - NUXT_PUBLIC_TYPEWRITER_DELAY=50 # The delay time of the typewriter effect, default 50ms
    depends_on:
      - backend-web-server
    ports:
      - '${CLIENT_PORT:-80}:80'
        #- '${CLIENT_PORT:-8585}:8585'
    networks:
      - yachat-ui_network
    restart: always

  backend-wsgi-server:
    platform: linux/x86_64
    #image: hdrbv/yachat-ui-wsgi-server:latest
    build:
      context: ./back_end_server
      dockerfile: Dockerfile
      target: wsgi-server
    environment:
      APP_DOMAIN: localhost:9000
      WORKER_TIMEOUT: 180
      DJANGO_SUPERUSER_USERNAME: superuser # default superuser name (admin)
      DJANGO_SUPERUSER_PASSWORD: pass_25 # default superuser password (password)
      DJANGO_SUPERUSER_EMAIL: admin@example.com # default superuser email
      ACCOUNT_EMAIL_VERIFICATION: ${ACCOUNT_EMAIL_VERIFICATION:-none} # Determines the e-mail verification method during signup – choose one of "none", "optional", or "mandatory". Default is "optional". If you don't need to verify the email, you can set it to "none".
      # If you want to use the email verification function, you need to configure the following parameters
#     - EMAIL_HOST=SMTP server address
#     - EMAIL_PORT=SMTP server port
#     - EMAIL_HOST_USER=
#     - EMAIL_HOST_PASSWORD=
#     - EMAIL_USE_TLS=True
#     - EMAIL_FROM=no-reply@example.com  #Default sender email address
      DB_URL: ${DB_URL:-sqlite:///db.sqlite3}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3    
    ports:
       - '${WSGI_PORT:-8000}:8000'
    # ports:
    #   - '8000:8000'
    networks:
      - yachat-ui_network
    restart: always
    
  backend-web-server:
    platform: linux/x86_64
    build:
      context: ./back_end_server
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8000
    ports:
      - '${SERVER_PORT:-9000}:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - yachat-ui_network
    restart: always

networks:
  yachat-ui_network:
    driver: bridge
    
